apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: GoCloudEKS
  region: ap-northeast-2
  version: "1.20"

vpc:
  id: "vpc-0dbe9934fd20c46b2"  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.0.0/16"       # (optional, must match CIDR used by the given VPC)
  nat:
    gateway: "Disable"
  subnets:
    public: 
      public-2a: 
        id: "subnet-082f4c3b27c19d5d3"
        cidr: "192.168.0.0/24"
      public-2c: 
        id: "subnet-0a99b84ed5c26a49d"
        cidr: "192.168.32.0/24"
    private:
      private-2a:
        id: "subnet-0fed7ecc5183b4e3e"
        cidr: "192.168.64.0/24" # (optional, must match CIDR used by the given subnet)
      private-2c:
        id: "subnet-08583e08738fdada9"
        cidr: "192.168.96.0/24"  # (optional, must match CIDR used by the given subnet)

# 기존 생성된 vpc 영역을 사용하는 경우, 사용할 수 없는 속성
#availabilityZones: 
#  - "ap-northeast-2a"
#  - "ap-northeast-2b"
 
managedNodeGroups:
  - name: JavaNode
    instanceType: t2.large
    instanceName: "JavaInstance"
    minSize: 2
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 10
    privateNetworking: true
    ssh: 
      allow: true
    availabilityZones: 
      - "ap-northeast-2a"
      - "ap-northeast-2c"
    iam: 
      withAddonPolicies: 
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        externalDNS: true
        certManager: true
        albIngress: true
        cloudWatch: true

  - name: WPNode
    instanceType: t2.large
    instanceName: "WPInstance"
    minSize: 2
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 10
    privateNetworking: true
    ssh: 
      allow: true
    availabilityZones: 
      - "ap-northeast-2a"
      - "ap-northeast-2c"
    iam: 
      withAddonPolicies: 
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        externalDNS: true
        certManager: true

  - name: JenkinsNode
    instanceType: t2.large
    instanceName: "JenkinsInstance"
    minSize: 2
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 10
    privateNetworking: true
    ssh: 
      allow: true
    availabilityZones: 
      - "ap-northeast-2a"
      - "ap-northeast-2c"
    iam: 
      withAddonPolicies: 
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        externalDNS: true
        certManager: true

cloudWatch: 
  clusterLogging: 
    enableTypes: ["*"]
