apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: GoCloudEKS
  region: ap-northeast-2
  version: "1.20"

vpc:
  id: "vpc-0dc1cc81d016964e7"  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.0.0/16"       # (optional, must match CIDR used by the given VPC)
  nat:
    gateway: "Disable"
  subnets:
    public: 
      public-2a: 
        id: "subnet-091cd2b73fd3554d2"
        cidr: "192.168.0.0/24"
      public-2c: 
        id: "subnet-099726cbd04a1c40d"
        cidr: "192.168.32.0/24"
    private:
      private-2a:
        id: "subnet-0bafcf56aaa11e246"
        cidr: "192.168.64.0/24" # (optional, must match CIDR used by the given subnet)
      private-2c:
        id: "subnet-098c97497107d5a20"
        cidr: "192.168.96.0/24"  # (optional, must match CIDR used by the given subnet)

# 기존 생성된 vpc 영역을 사용하는 경우, 사용할 수 없는 속성
#availabilityZones: 
#  - "ap-northeast-2a"
#  - "ap-northeast-2b"
 
managedNodeGroups:
  - name: JavaNode
    instanceType: t2.large
    instanceName: "JavaInstance"
    minSize: 2
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 10
    privateNetworking: true
    ssh: 
      allow: true
    availabilityZones: 
      - "ap-northeast-2a"
      - "ap-northeast-2c"
    iam: 
      withAddonPolicies: 
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        externalDNS: true
        certManager: true
        albIngress: true
        cloudWatch: true

#  - name: WPNode
#    instanceType: t2.large
#    instanceName: "WPInstance"
#    minSize: 2
#    desiredCapacity: 2
#    maxSize: 3
#    volumeSize: 10
#    privateNetworking: true
#    ssh: 
#      allow: true
#    availabilityZones: 
#      - "ap-northeast-2a"
#      - "ap-northeast-2c"
#    iam: 
#      withAddonPolicies: 
#        imageBuilder: true
#        autoScaler: true
#        ebs: true
#        efs: true
#        externalDNS: true
#        certManager: true

  - name: JenkinsNode
    instanceType: t2.large
    instanceName: "JenkinsInstance"
    minSize: 2
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 10
    privateNetworking: true
    ssh: 
      allow: true
    availabilityZones: 
      - "ap-northeast-2a"
      - "ap-northeast-2c"
    iam: 
      withAddonPolicies: 
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        externalDNS: true
        certManager: true

cloudWatch: 
  clusterLogging: 
    enableTypes: ["*"]
