apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-app
spec:
<<<<<<< HEAD:app/wordpress.yaml
  replicas: 2
=======
  replicas: 3
>>>>>>> 74b8339... pod 증가 테스트 완료 3개 base로 최적화:manifest/wordpress/base/wordpress.yaml
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: user
        - name: WORDPRESS_DB_PASSWORD
          value: password
        - name: WORDPRESS_DB_HOST
<<<<<<< HEAD:app/wordpress.yaml
          value: mysql-clusterip:3306

        volumeMounts:
          - name: wordpress-vol  # match volumes
            mountPath: /var/www/html
      volumes:
        - name: wordpress-vol # match volumeMounts
          persistentVolumeClaim:
            claimName: wordpress-pvc
            
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: ng-private
=======
          value: wordpress.cfgwexy8deov.ap-northeast-2.rds.amazonaws.com
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: WPNode
---
>>>>>>> 2916bde... 발표용 소스 최적화 - 형상 관리용:manifest/wordpress/base/wordpress.yaml
