apiVersion: v1
kind: Service
metadata:
  name: webserver
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0348137bf4ed4e43a
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - port: 80
